spring:
    application:
        name: sistemabecas-auth
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://db:3306/sistemabecas?useSSL=true&allowPublicKeyRetrieval=true
        username: root
        password: ${MYSQL_ROOT_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

tokens:
    jwt-token: ${JWT_TOKEN}
